apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: system:openshift:operator:cluster-kube-apiserver-operator
roleRef:
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  namespace: openshift-cluster-kube-apiserver-operator
  name: openshift-cluster-kube-apiserver-operator
