apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: openshift-kube-apiserver-operator
  name: kube-apiserver-operator
  labels:
    app: kube-apiserver-operator
  annotations:
    include.release.openshift.io/self-managed-high-availability: "true"

