apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: kube-apiserver
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
spec: {}
status:
  versions:
  - name: operator
    version: "0.0.1-snapshot"
  - name: raw-internal
    version: "0.0.1-snapshot"
  - name: kube-apiserver
    version: "0.0.1-snapshot-kubernetes"
  relatedObjects:
    - group: operator.openshift.io
      name: cluster
      resource: kubeapiservers
    - group: apiextensions.k8s.io
      name: ""
      resource: customresourcedefinitions
    - group: security.openshift.io
      name: ""
      resource: securitycontextconstraints
    - group: ""
      name: openshift-config
      resource: namespaces
    - group: ""
      name: openshift-config-managed
      resource: namespaces
    - group: ""
      name: openshift-kube-apiserver-operator
      resource: namespaces
    - group: ""
      name: openshift-kube-apiserver
      resource: namespaces
    - group: admissionregistration.k8s.io
      resource: mutatingwebhookconfigurations
    - group: admissionregistration.k8s.io
      resource: validatingwebhookconfigurations
