apiVersion: v1
kind: ConfigMap
metadata:
  namespace: openshift-core-operators
  name: openshift-cluster-kube-apiserver-operator-config
data:
  config.yaml: |
    apiVersion: operator.openshift.io/v1alpha1
    kind: GenericOperatorConfig
