apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: openshift-kube-apiserver
  name: apiserver
  labels:
    app: openshift-kube-apiserver
    apiserver: "true"
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: openshift-kube-apiserver
      apiserver: "true"
  template:
    metadata:
      name: openshift-kube-apiserver
      labels:
        app: openshift-kube-apiserver
        apiserver: "true"
    spec:
      serviceAccountName: openshift-kube-apiserver-sa
      containers:
      - name: apiserver
        image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        command: ["hypershift", "openshift-kube-apiserver"]
        args:
        - "--config=/var/run/configmaps/config/config.yaml"
        ports:
        - containerPort: 6443
        volumeMounts:
        - mountPath: /var/run/configmaps/config
          name: config
        - mountPath: /var/run/configmaps/aggregator-client-ca
          name: aggregator-client-ca
        - mountPath: /var/run/configmaps/client-ca
          name: client-ca
        - mountPath: /var/run/configmaps/etcd-serving-ca
          name: etcd-serving-ca
        - mountPath: /var/run/configmaps/kubelet-serving-ca
          name: kubelet-serving-ca
        - mountPath: /var/run/configmaps/sa-token-signing-certs
          name: sa-token-signing-certs
        - mountPath: /var/run/secrets/aggregator-client
          name: aggregator-client
        - mountPath: /var/run/secrets/etcd-client
          name: etcd-client
        - mountPath: /var/run/secrets/kubelet-client
          name: kubelet-client
        - mountPath: /var/run/secrets/serving-cert
          name: serving-cert
      volumes:
      - name: config
        configMap:
          name: deployment-apiserver-config
      - name: aggregator-client-ca
        configMap:
          name: aggregator-client-ca
      - name: client-ca
        configMap:
          name: client-ca
      - name: etcd-serving-ca
        configMap:
          name: etcd-serving-ca
      - name: kubelet-serving-ca
        configMap:
          name: kubelet-serving-ca
      - name: sa-token-signing-certs
        configMap:
          name: sa-token-signing-certs
      - name: aggregator-client
        secret:
          secretName: aggregator-client
      - name: etcd-client
        secret:
          secretName: etcd-client
      - name: kubelet-client
        secret:
          secretName: kubelet-client
      - name: serving-cert
        secret:
          secretName: serving-cert
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - operator: Exists
