# this is written by the kcm-o, but we initialize here to cleanly handle the adoption case
apiVersion: v1
kind: ConfigMap
metadata:
  name: sa-token-signing-certs
  namespace: openshift-config-managed
data:
  service-account-001.pub: |
    '{{ .Assets | load "service-account.pub" | indent 4 }}'
