apiVersion: migration.k8s.io/v1alpha1
kind: StorageVersionMigration
metadata:
  name: flowcontrol-prioritylevel-storage-version-migration
spec:
  resource:
    group: flowcontrol.apiserver.k8s.io
    version: v1beta1
    resource: prioritylevelconfigurations
